### ISSUE TITLE
Is perl 5.12 requirement intentional?

### ISSUE THREAD

**Issue by charsbar** [rjbs/Email-Date-Format#6]
Hi, I am surprised that Email::Date::Format 1.006 now requires perl 5.012 ( https://metacpan.org/release/RJBS/Email-Date-Format-1.006/source/META.json) , instead of 5.006. because of package version (https://metacpan.org/release/RJBS/Email-Date-Format-1.006/source/lib/Email/Date/Format.pm#L4 ). This breaking change seems not described in the Changes file. Is this intentional or just by accident?

**Comment by rjbs** [comment]
I'd put it somewhere between intentional and accident.  My stock configuration has begun adding a "what age of Perl will this library support" section, and as I release versions with that, some are also automatically updated to get built in a way compatible with that version.  Generally, that just means that "package NAME VERSION" may be used.

For Email::Date::Format, you'll see that [it's marked "long term" support](https://metacpan.org/release/RJBS/Email-Date-Format-1.006/view/lib/Email/Date/Format.pm#PERL-VERSION), meaning five years of perls.

This is the second (I think) report I've gotten for a change like this.  I will try to be more careful about updating changelogs, and apologize for any inconvenience I've caused!
